# Generated by Django 4.1 on 2022-10-18 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_experience',
            new_name='tea_experience',
        ),
    ]
