# Generated by Django 4.1 on 2022-10-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0002_rename_teacher_experience_teacher_tea_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_gender',
        ),
    ]
