# Generated by Django 4.1 on 2022-10-18 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0003_remove_teacher_teacher_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_address',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_password',
        ),
    ]
