# Generated by Django 4.1 on 2022-10-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0004_remove_teacher_teacher_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_uid', models.CharField(max_length=30)),
                ('admin_pswd', models.CharField(max_length=40)),
            ],
        ),
    ]
